apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloth
  template:
    metadata:
      labels:
        app: cloth
    spec:
      containers:
        - name: cloth
          image: fujinugraha/cloth:api-driven
          env:
            - name: MONGO_URI
              value: "mongodb://cloth-mongo-clusterip-srv:27017/cloth"
            - name: STOCK_API_URI
              value: "http://stock-clusterip-srv:3000"
            - name: SALE_API_URI
              value: "http://sale-clusterip-srv:3000"
---
apiVersion: v1
kind: Service
metadata:
  name: cloth-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: cloth
  ports:
    - name: cloth
      protocol: TCP
      port: 3000
      targetPort: 3000
