apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock
  template:
    metadata:
      labels:
        app: stock
    spec:
      containers:
        - name: stock
          image: fujinugraha/stock:api-driven
          env:
            - name: MONGO_URI
              value: "mongodb://stock-mongo-clusterip-srv:27017/stock"
            - name: CLOTH_API_URI
              value: "http://cloth-clusterip-srv:3000"
---
apiVersion: v1
kind: Service
metadata:
  name: stock-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: stock
  ports:
    - name: stock
      protocol: TCP
      port: 3000
      targetPort: 3000
